/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DepositHistoryRouteImport } from './routes/deposit-history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WithdrawHistoryRouteImport } from './routes/withdraw-history'
import { Route as ApiPublicCheckoutSessionRouteImport } from './routes/api/public/checkout/session'
import { Route as ApiPublicCheckoutSubmitRouteImport } from './routes/api/public/checkout/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositHistoryRoute = DepositHistoryRouteImport.update({
  id: '/deposit-history',
  path: '/deposit-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawHistoryRoute = WithdrawHistoryRouteImport.update({
  id: '/withdraw-history',
  path: '/withdraw-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutSessionRoute =
  ApiPublicCheckoutSessionRouteImport.update({
    id: '/api/public/checkout/session',
    path: '/api/public/checkout/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckoutSubmitRoute = ApiPublicCheckoutSubmitRouteImport.update({
  id: '/api/public/checkout/submit',
  path: '/api/public/checkout/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/deposit-history': typeof DepositHistoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more': typeof MoreRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/referrals': typeof ReferralsRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/withdraw-history': typeof WithdrawHistoryRoute
  '/api/public/checkout/session': typeof ApiPublicCheckoutSessionRoute
  '/api/public/checkout/submit': typeof ApiPublicCheckoutSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/deposit-history': typeof DepositHistoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more': typeof MoreRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/referrals': typeof ReferralsRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/withdraw-history': typeof WithdrawHistoryRoute
  '/api/public/checkout/session': typeof ApiPublicCheckoutSessionRoute
  '/api/public/checkout/submit': typeof ApiPublicCheckoutSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/deposit-history': typeof DepositHistoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investments': typeof InvestmentsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/more': typeof MoreRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/referrals': typeof ReferralsRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/withdraw-history': typeof WithdrawHistoryRoute
  '/api/public/checkout/session': typeof ApiPublicCheckoutSessionRoute
  '/api/public/checkout/submit': typeof ApiPublicCheckoutSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/deposit'
    | '/deposit-history'
    | '/forgot-password'
    | '/investments'
    | '/leaderboard'
    | '/more'
    | '/plans'
    | '/profile'
    | '/promo'
    | '/referrals'
    | '/salary'
    | '/sitemap.xml'
    | '/transactions'
    | '/withdraw'
    | '/withdraw-history'
    | '/api/public/checkout/session'
    | '/api/public/checkout/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/deposit'
    | '/deposit-history'
    | '/forgot-password'
    | '/investments'
    | '/leaderboard'
    | '/more'
    | '/plans'
    | '/profile'
    | '/promo'
    | '/referrals'
    | '/salary'
    | '/sitemap.xml'
    | '/transactions'
    | '/withdraw'
    | '/withdraw-history'
    | '/api/public/checkout/session'
    | '/api/public/checkout/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/deposit'
    | '/deposit-history'
    | '/forgot-password'
    | '/investments'
    | '/leaderboard'
    | '/more'
    | '/plans'
    | '/profile'
    | '/promo'
    | '/referrals'
    | '/salary'
    | '/sitemap.xml'
    | '/transactions'
    | '/withdraw'
    | '/withdraw-history'
    | '/api/public/checkout/session'
    | '/api/public/checkout/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  DepositHistoryRoute: typeof DepositHistoryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MoreRoute: typeof MoreRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  PromoRoute: typeof PromoRoute
  ReferralsRoute: typeof ReferralsRoute
  SalaryRoute: typeof SalaryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
  WithdrawHistoryRoute: typeof WithdrawHistoryRoute
  ApiPublicCheckoutSessionRoute: typeof ApiPublicCheckoutSessionRoute
  ApiPublicCheckoutSubmitRoute: typeof ApiPublicCheckoutSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-history': {
      id: '/deposit-history'
      path: '/deposit-history'
      fullPath: '/deposit-history'
      preLoaderRoute: typeof DepositHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw-history': {
      id: '/withdraw-history'
      path: '/withdraw-history'
      fullPath: '/withdraw-history'
      preLoaderRoute: typeof WithdrawHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/session': {
      id: '/api/public/checkout/session'
      path: '/api/public/checkout/session'
      fullPath: '/api/public/checkout/session'
      preLoaderRoute: typeof ApiPublicCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/submit': {
      id: '/api/public/checkout/submit'
      path: '/api/public/checkout/submit'
      fullPath: '/api/public/checkout/submit'
      preLoaderRoute: typeof ApiPublicCheckoutSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  DepositHistoryRoute: DepositHistoryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvestmentsRoute: InvestmentsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MoreRoute: MoreRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  PromoRoute: PromoRoute,
  ReferralsRoute: ReferralsRoute,
  SalaryRoute: SalaryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
  WithdrawHistoryRoute: WithdrawHistoryRoute,
  ApiPublicCheckoutSessionRoute: ApiPublicCheckoutSessionRoute,
  ApiPublicCheckoutSubmitRoute: ApiPublicCheckoutSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
